[build]
    base    = ""
    publish = "build"
    command = "REACT_APP_STAGE=dev react-scripts build"

[context.production]
    command = "REACT_APP_STAGE=prod react-scripts build"

[context.deploy-preview]
    command = "REACT_APP_STAGE=dev react-scripts build"

[context.branch-deploy]
    command = "REACT_APP_STAGE=dev react-scripts build"